name: Run Python Tests

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main]
  workflow_dispatch: # Allow manual triggering

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macos-latest]
        os: [ubuntu-latest] # The postgres that comes with Github Actions is ubuntu only
        python-version: [3.13]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Start postgresql
      run: |
        sudo systemctl start postgresql.service
        pg_isready
        sudo -u postgres createuser -s -d -r -w runner
    
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Create virtual environment and install dependencies
      run: |
        uv venv --python ${{ matrix.python-version }}
        uv pip install -e ".[dev]"

    - name: Run tests with pytest
      run: |
        uv run pytest tests/ -v --tb=short
      